### ISSUE TITLE
Flutter doc AndroidManifest.xml inline comment error

### ISSUE THREAD

**Issue by joyzoursky** [authgear/docs#129]
Get error when copy and paste the AndroidManifest.xml code change:

```
Error parsing LocalFile:
'my-directory/android/app/src/main/AndroidManifest.xml'
Please ensure that the android manifest is a valid XML document and try again.
```

The comment is on the wrong line
<img width="1280" alt="Screenshot 2022-11-17 at 6 25 31 PM" src="https://user-images.githubusercontent.com/12539486/202421924-b7cfb981-6d09-44a7-a067-d4a913e9776f.png">

**Comment by louischan-oursky** [comment]
https://github.com/authgear/docs/commit/3411e1204cca40f951d25e56b12961bd7c331a72

Just realized comment is disallowed within the open tag :(
