### ISSUE TITLE
Examples and more detailed description on Audit log

### ISSUE THREAD

**Issue by fungc-io** [authgear/docs#136]
In the audit log doc page: https://docs.authgear.com/monitor/audit-log

Add more description of the audit log events, and example of the events data

**Comment by Boburmirzo** [comment]
@fungc-io Do you think this information is enough? Currently, we have:

https://docs.authgear.com/how-to-guide/monitor/audit-log

**Comment by fungc-io** [comment]
@Boburmirzo ,
It will be helpful if we provide some short explanations to each event.

And add documentation for the "admin API and Portal" log
<img width="1269" alt="image" src="https://github.com/authgear/docs/assets/15207470/c76f3688-e86e-48bb-b62c-f01040ef3bfb">

**Comment by fungc-io** [comment]
Fixed in https://github.com/authgear/docs/commit/cf478cd550a8dad621d73fad6961359f7a99bfe5#diff-ae0ecf8f33b8f5d383e584193d5dfef4c26ba9fd2f5a94a4b6c380f8326b03e1
