### ISSUE TITLE
Update Passkey compatibility description

### ISSUE THREAD

**Issue by fungc-io** [authgear/docs#138]
https://docs.authgear.com/strategies/passkeys

Chrome and Android had released updates

Reference:
https://developers.google.com/identity/passkeys/supported-environments

**Comment by Boburmirzo** [comment]
@fungc-io I updated Android support on the same page:

https://docs.authgear.com/strategies/passkeys

![image](https://github.com/authgear/docs/assets/14247607/aa9a61ff-2995-410f-85f7-ff48372dc8c8)

**Comment by fungc-io** [comment]
@Boburmirzo i think we can remove "Google have also..." in that case?

**Comment by Boburmirzo** [comment]
Sounds good! It also got removed

![image](https://github.com/authgear/docs/assets/14247607/0da334a3-589f-46f9-80a0-a98781384194)
