### ISSUE TITLE
Replace all [authgearapps.com] to [your authgear endpoint]

### ISSUE THREAD

**Issue by chpapa** [authgear/docs#148]
1. We do not use authgearapps.com anymore
2. Avoid further issues and for better documentation.

Not urgent, just creating this as a reminder

**Comment by Boburmirzo** [comment]
@chpapa I do not see anymore authgearapps.com, it seems that someone has already replaced it to: authgear-apps.com and your authgear endpoint. 

Could you show me an example if you saw it somewhere else?

**Comment by chpapa** [comment]
Ah I'm just creating this as a reminder to final check.

Just do a quick grep, it seems only at:

how-to-guide/authenticate/local-cookie-based-web-setup.md:    set $resolver https://{PROJECT_NAME}.authgearapps.com/_resolver/resolve;
reference/apis/api-for-client-applications.md:Here is [an example of how it looks](https://accounts.portal.authgearapps.com/.well-known/openid-configuration).

**Comment by Boburmirzo** [comment]
@chpapa Now they got fixed too. We can close the issue.
