### ISSUE TITLE
Define "Password Strength" in doc

### ISSUE THREAD

**Issue by fungc-io** [authgear/docs#150]
We do offer "Password Strength" in password policy, however it's not known to the users what the strength means.
It'd be great if we can provide more info on it. 
If a public algorithm/public library is used, we can link to the repo of it.

**Comment by fungc-io** [comment]
@louischan-oursky how is the password strength currently calculated?

**Comment by louischan-oursky** [comment]
With this algorithm https://github.com/dropbox/zxcvbn

**Comment by buildbro** [comment]
I've added a page for password strength to the documentation site. It's not published yet, but you can check the draft under the security sub-section.

**Comment by fungc-io** [comment]
Thanks @buildbro I've published the doc!
