### ISSUE TITLE
Explain setting pages requests

### ISSUE THREAD

**Issue by mr9dollars** [authgear/docs#17]
https://tools.ietf.org/html/rfc8252#section-8.12

- Follow-up solution converted to issue #761
- Documentation

**Comment by chpapa** [comment]
btw, actually, we should have getting start guide for integrating with iOS/Android/Web SPA/Web SSR.

And the setting page request require the account ID should be in the guide about Web SSR I  think. (Since other platforms SDK would automatically do it already)
