### ISSUE TITLE
Document how to edit template

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/docs#22]
- Template are written using Go template. The official documentation is the definitive way to learn that. https://golang.org/pkg/text/template/
- Do not know which template to edit. For example, the developer do not know which template to edit if they want to edit the one-time password code email during primary authentication. How should we present the full list to the developer to let them know available templates for editing? How do we explain the mapping between the name of the template (e.g. `forgot_password_email.html`) and when the user will receive the rendered template (e.g. the user will receive the email when they claims they forgot their password)

**Comment by Boburmirzo** [comment]
I do not think it is still relevant we can close this issue since it is not connected to Authgear docs anymore.
