### ISSUE TITLE
Add documentation on the role played by Authgear in OAuth and OIDC

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/docs#4]
Explain to developers who are familiar with OAuth and OIDC and they want to know what Authgear is.

---

A quote from Terry

> - OIDC has two party: Identity Provider(IdP) and Relying Party(RP)
> - RP is the OAuth client, IdP is the OAuth server
> - Authgear can act as RP to other IdP, e.g. Google, Facebook
> - Authgear can also act as IdP to RPs, e.g. your developed mobile app, website, etc.
> - Basically, Authgear is a identity federation gateway

**Comment by Boburmirzo** [comment]
@louischan-oursky I improved docs with the Identity concepts that explain above:

https://docs.authgear.com/how-to-guide-1/identity-fundamentals

You can also refer to the Authgear use-cases page:

https://docs.authgear.com/how-to-guide-1/authgear-use-cases

**Comment by louischan-oursky** [comment]
Thank you!
