### ISSUE TITLE
Revise "Setup Application in Authgear" section on SDK Get Started pages

### ISSUE THREAD

**Issue by joyzoursky** [authgear/docs#83]
There are a few problems I faced while trying to following the "Setup Application in Authgear" on the following pages, and configure with my app (the internal demo app) for quick try.
- Xamarin SDK
- Flutter SDK
- React Native SDK
- Android SDK
- iOS SDK
- Web SDK

Please try to rewrite the section to resolve the following problems a new dev will face.

Problems:
1. **Step 1:** It should start with creating the project and selecting it. Users new to authgear may misunderstand that "Applications" = "Projects" and get confused.
2. **Step 2:** "Add Application" is not on the top right corner in the portal
3. **Step 3:** What's mean by `this is for reference only`? What or whose reference? And better to have an example here
4. **Step 4:** What's a custom scheme? How should I define it for my project? Since there is no public demo app now, cannot just use a sample URI to plug and play, could reference user to the section teaching how to make this. 
5. **Step 4 & 5:** The steps for Add URI is unclear, please write in 1 step for each click, e.g. Click XX, Click XX, Back to Applications page, Copy the "Client ID" for later use.
6. **JWT tooltip:** Too much unknown terms for new dev to see the tool tip for JWT access token and may get a bit shocked: JWT access token? forward incoming requests, what requests will they be? Authgear "Resolver" Endpoint is another thing? Suggest extracting this tooltip section from the simple step-by-step guide above. If possible please also revise the tooltip to explain or add reference links for the terms.
7. Suggest adding a screenshot for a correct setup sample.

<img width="877" alt="Screenshot 2022-05-23 at 12 22 33 PM 1" src="https://user-images.githubusercontent.com/12539486/169745583-6c41ae20-aea9-4c72-92c8-a568fbe64525.png">

**Comment by stanleylhs** [comment]
@joyzoursky Re: problem 3, the word URI is missing, it means Custom URI Scheme. 

ref: https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app

**Comment by joyzoursky** [comment]
@stanleylhs Thanks, and we should have links for the internal / external references here, seem on some sdk get started pages there are part of the instructions for registering URL scheme. https://docs.authgear.com/get-started/ios#register-url-scheme-for-redirect-uri

**Comment by stanleylhs** [comment]
This is my end of day current draft. Will work on it later.

1. From the project listing, select an existing projects or create a new one
2. Go to "Applications".
3. Click "⊕Add Application" in the top left tool bar
4. Input the name of your application, e.g. "AwesomeApps", for future reference.
5. In your target platform IDE (XCode / Android Studio), define a custom URI scheme that the users will be redirected back to your app after they have authenticated with Authgear. See external info below.
6. Add the URI to "Redirect URIs". (e.g. com.myapp.example://host/path).
7. Click "Save" and make a note of the "Client ID". You can also obtain the "Client ID" from the list again.
 
If you want to validate JWT access token in your server, select Issue JWT as access token. If you will forward incoming requests to Authgear Resolver Endpoint for authentication, leave this unchecked. See comparisons in [Backend Integration](https://github.com/get-started/backend-integration).


Ref for Custom URL scheme: 
iOS https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app
Android https://developer.android.com/training/app-links/deep-linking
