### ISSUE TITLE
Document how to find an user given their email is known

### ISSUE THREAD

**Issue by louischan-oursky** [authgear/docs#86]

**Comment by carmenlau** [comment]
May I have more background about this issue? Is it about explaining how to search for a user by email via admin API?

**Comment by fungc-io** [comment]
@louischan-oursky 
Do you mean that?
If so, I think a a page here will be useful:

`apis/admin-apis/...`

<img width="318" alt="Screenshot 2022-09-01 at 06 33 50" src="https://user-images.githubusercontent.com/15207470/187839016-bf7ddd63-b553-454a-80d1-bb01e427127b.png">

A page about "Searching for a user" then some examples of how to search a user with their attributes, identify, etc.
