### ISSUE TITLE
Clarify webhooks page

### ISSUE THREAD

**Issue by fungc-io** [authgear/docs#97]
- How to know if a user is verified at webhook?
- It's unclear if the user profile update includes the change of verified values or not. Maybe we should fix it by, instead of just putting /*...*/ everywhere, be clear about what objects are included.

**Comment by carmenlau** [comment]
> How to know if a user is verified at webhook?

Currently, we can check the `is_verified` flag in the user payload to identify if the user is verified. The flag will change if the user verifies through signup, login, or update login id... etc. 

But if the user triggers verification from the settings, we don't have any webhook for that case. We may consider adding one.
